### ISSUE TITLE
Getting issue of X-api-key while running this project

### ISSUE THREAD

**Issue by gshrey2002** [unusualcodeorg/gomicro#2]
Hi @janishar ,

I am encountering an issue with running the project's API. It requires an x-api-key, which is not provided. In the API documentation, the API key is listed as "....." only, making it impossible to access the project's APIs.

Could you please provide guidance on how to obtain the correct API key?

**Comment by janishar** [comment]
HI @gshrey2002 The default API Key is `1D3F2DD1A5DE725DD4DF1D82BBB37 `. 
You can find the same in the mongo. 
You can connect to mongo using compass, localhost:27017  user: `admin`, password: `changeit`
